<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="App_Plugins\GoCo.Plugins\colorPalette\colorPalette.css" />
    <Content Include="App_Plugins\GoCo.Plugins\common\tab-accordions.css" />
    <Content Include="App_Plugins\GoCo.Plugins\design\preview\footer.html" />
    <Content Include="App_Plugins\GoCo.Plugins\design\preview\mainNav.html" />
    <Content Include="App_Plugins\GoCo.Plugins\design\fontSettings\google-web-font-list.json" />
    <Content Include="App_Plugins\GoCo.Plugins\heading\heading.css" />
    <Content Include="App_Plugins\GoCo.Plugins\heading\heading.html" />
    <Content Include="App_Plugins\GoCo.Plugins\radioButtonPlus\radioButtonPlus.css" />
    <Content Include="App_Plugins\GoCo.Plugins\blockPreview\blockPreview.html" />
    <Content Include="App_Plugins\GoCo.Plugins\backgroundColor\backgroundColor.html" />
    <Content Include="App_Plugins\GoCo.Plugins\colorPalette\colorPalette.html" />
    <Content Include="App_Plugins\GoCo.Plugins\baselineColorPicker\baselineColorPicker.css" />
    <Content Include="App_Plugins\GoCo.Plugins\baselineColorPicker\baselineColorPicker.html" />
    <Content Include="App_Plugins\GoCo.Plugins\numericPlus\numericPlus.html" />
    <Content Include="App_Plugins\GoCo.Plugins\radioButtonPlus\radioButtonPlus.html" />
    <Content Include="App_Plugins\GoCo.Plugins\radioButtonPlus\radioButtonPlus_Prevalue.html" />
    <Content Include="App_Plugins\GoCo.Plugins\buttonColor\buttonColor.html" />
    <Content Include="App_Plugins\GoCo.Plugins\togglePlus\togglePlus.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms" Version="13.5.2" />
  </ItemGroup>

  <ItemGroup>
    <!-- Opt-in to app-local ICU to ensure consistent globalization APIs across different platforms -->
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="72.1.0.3" />
    <PackageReference Include="Umbraco.Community.BlockPreview" Version="1.10.4" />
    <ProjectReference Include="..\GoCoSiteBuilder.Core\GoCoSiteBuilder.Core.csproj" />
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="72.1.0.3" Condition="$(RuntimeIdentifier.StartsWith('linux')) or $(RuntimeIdentifier.StartsWith('win')) or ('$(RuntimeIdentifier)' == '' and !$([MSBuild]::IsOSPlatform('osx')))" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="App_Plugins\GoCo.Plugins\blockPreview\img\" />
    <Folder Include="wwwroot\img\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="App_Plugins\GoCo.Plugins\blockPreview\blockPreview.controller.js" />
    <None Include="App_Plugins\GoCo.Plugins\backgroundColor\backgroundColor.controller.js" />
    <None Include="App_Plugins\GoCo.Plugins\colorPalette\colorPalette.controller.js" />
    <None Include="App_Plugins\GoCo.Plugins\baselineColorPicker\baselineColorPicker.controller.js" />
    <None Include="App_Plugins\GoCo.Plugins\design\colorSettings\colorSettings.controller.js" />
    <None Include="App_Plugins\GoCo.Plugins\design\colorSettings\colorSettings.css" />
    <None Include="App_Plugins\GoCo.Plugins\design\colorSettings\colorSettings.html" />
    <None Include="App_Plugins\GoCo.Plugins\design\fontSettings\fontSettings.css" />
    <None Include="App_Plugins\GoCo.Plugins\design\fontSettings\fontSettings.html" />
    <None Include="App_Plugins\GoCo.Plugins\design\fontSettings\fontSettings.controller.js" />
    <None Include="App_Plugins\GoCo.Plugins\heading\heading.controller.js" />
    <None Include="App_Plugins\GoCo.Plugins\numericPlus\numericPlus.controller.js" />
    <None Include="App_Plugins\GoCo.Plugins\radioButtonPlus\radioButtonPlus.controller.js" />
    <None Include="App_Plugins\GoCo.Plugins\radioButtonPlus\radioButtonPlus_Prevalue.controller.js" />
    <None Include="App_Plugins\GoCo.Plugins\design\design.service.js" />
    <None Include="App_Plugins\GoCo.Plugins\buttonColor\buttonColor.controller.js" />
    <None Include="App_Plugins\GoCo.Plugins\togglePlus\togglePlus.controller.js" />
    <None Include="App_Plugins\GoCo.Plugins\package.manifest" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Razor files are needed for the backoffice to work correctly -->
    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Remove RazorCompileOnBuild and RazorCompileOnPublish when not using ModelsMode InMemoryAuto -->
    <RazorCompileOnBuild>false</RazorCompileOnBuild>
    <RazorCompileOnPublish>false</RazorCompileOnPublish>
  </PropertyGroup>

</Project>
