<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ViewModels\HeadingViewModel.cs~RF129c1911.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Umbraco.Cms.Core" Version="13.5.0" />
    <PackageReference Include="Umbraco.Cms.Web.BackOffice" Version="13.5.0" />
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="13.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GoCoSiteBuilder.Models\GoCoSiteBuilder.Models.csproj" />
  </ItemGroup>
</Project>
